spring:
  application:
    name: case-validation-server

server:
  port: 5011

network-store-server:
  base-uri: http://localhost:8080

backing-services:
  loadflow-server:
    base-uri: http://localhost:5008